### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'includes')

### ISSUE THREAD

**Issue by magnum6actual** [ilmoi/nft-armory#10]
Running this no changes from github, I get the undefined error here in main.ts:

 if (process.env.VUE_APP_MAINNET_URL!.includes('genesysgo')) {
	console.log('powered by gg');
  }

Everything runs fine if I comment this out. I'm assuming you've got VUE_APP_MAINNET_URL defined in a .env file that's not in the repository.

**Comment by ilmoi** [comment]
that's correct, I should probably fix to
```
if (process.env.VUE_APP_MAINNET_URL && process.env.VUE_APP_MAINNET_URL!.includes('genesysgo'))
```

**Comment by ilmoi** [comment]
done see latest pr
